print("Enter customer name: ")
customername = input()
print("Enter item purchased: ")
itempurchased  = input()
print("Hello, " + str(customername) + " You have purchased " + str(itempurchased) )
